apiVersion: v1
kind: Secret
metadata:
  name: pixabay-apikey
data:
  API_KEY: ENC[AES256_GCM,data:VA7f8rWwH4mWpTjXZYLpBXwQ4Gn+4XZcgdUEnPs6a6FBV/EtCLLtiY+Sk+kAxN7O,iv:aeMfUCG+vbvD/5qRXcyMhQhrzOt5gvGbbm49hYfQ/Eg=,tag:P0n54qD240klReM6jZW4MA==,type:str]
sops:
  age:
    - recipient: age13qxz7x6y4pzw537s2arezlzvrzpxys7jf2y8xdcfce6ysc8xmd2s7zp6fc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSzhBVkNzRms0TUgxMi9H
        bHhDYVBSSXEreEVwN2ZiTnZwWHJPa09jYUZFCmMrY2krS3dlRGNQaTE1KzJ4R0dx
        V3VUK3VLQ1JyUkErMjZDK1FabGlXRGsKLS0tIEQ4N25ibk5KS0VPZjdFdEwyeEx3
        eWI3LzgwUWNSNXNWMm1MSVRvNFNvejgK+Lkydejh7zgvEThzLT2FqoWh/1wjXtqD
        2oCNZ5S3runHWwxi+TX10kXpCYBNRKivgKJPMF5+LXK9gfaLDN0Bwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T06:31:33Z"
  mac: ENC[AES256_GCM,data:vUw1kzsLiMjo+4IJH+/MlMvKFD92a4rJyfsveAJgdz/w/xCX2RF4vShYcKqse2ZEyZz7urK0DjHvqtfSZw0OrTI3MybrrMke9noWv/XOlpAMTNQ19BqePR25uKoJ9C+pUCE2uvXPqVZ3et0sZ7HLZhwMrcwzOmmr5K+0pptBTX8=,iv:DSYMYEKJxo97XiFghazznsh4SthZkd4nk+UGhwSUTSI=,tag:H7wiPljNhq63hCKs4ehGsg==,type:str]
  encrypted_regex: ^(data)$
  version: 3.12.1
