apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: log-and-ping-pv
          persistentVolumeClaim:
            claimName: log-and-ping-claim
      containers:
        - name: ping-pong
          image: autorejecttop/ping-pong:2.7
          imagePullPolicy: Always
          volumeMounts:
            - name: log-and-ping-pv
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: log-and-ping-configmap
                  key: postgres_hostname
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: log-and-ping-configmap
                  key: postgres_port
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: log-and-ping-configmap
                  key: postgres_database
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: log-and-ping-configmap
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-postgres-secret
                  key: postgres_password
