apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: ping-pong-postgres-secret
data:
    postgres_password: ENC[AES256_GCM,data:A3cc4X+56LKJKrgevDoBbg==,iv:jepezrVHuzANhyjSL3MuL6sCqpM63f/uMv/H0zC7sDM=,tag:m7BO2JU/vnWwC573RkByuw==,type:str]
sops:
    age:
        - recipient: age1wryhlkklnqngmvcewf8h6frnnxw4xvsah63ums9u2zejqkyh846swu9f90
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUEpWZ2VtSS9pN0FNYm1B
            MnJyQlIrT0tIVDMzc1hXZWNrUnZ1V29OcWlFCnR4bWsydXZBVjVDRVl1eVY2eGJj
            Zmt4ZEcwSk9WUXBiSEF6aGRzZjZkRk0KLS0tIDlDVzdSRjdQSzkyTDBDL1BVaDBE
            cG5WSW1xR3VxSno3dmViYlVjNm9BTzgKwSU4vH//0zvyjn3Q348mVu/iYKYuLND2
            PutTU/guN8wUDDPn3rU7fLSwRxFsgwA7eWiNdSTvMuN7LuYwNhs5cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T08:06:19Z"
    mac: ENC[AES256_GCM,data:K7uJkH5m5XKCTJpYYbPTa6aNIsFnH9MoULXS2wyNl+G1ee5BaSeL4yospruiYYBYR1Ngx/WpTXFXmvU/v2RN+dpsxxorWECiJfybvEDC62VAnivkk2FFyUC5wZTMJZErYtlWODG5mHQKeR/hPC9HE+R3OVeQKl1PFf5wJKiUu94=,iv:223AAbFiNOh2r0pDTAUaP7HTDwZT6BdOTCRlmY3xJI4=,tag:fz0kAnhXVd8h06dw4sfHLg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.1
