apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-postgres-service
  labels:
    app: ping-pong-postgres-app
spec:
  ports:
    - port: 5432
      name: db
  clusterIP: None
  selector:
    app: ping-pong-postgres-app
