apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend-deployment
  template:
    metadata:
      labels:
        app: todo-app-frontend-deployment
    spec:
      containers:
        - name: todo-app
          image: autorejecttop/todo-app-frontend:2.6
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: frontend_container_port
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: image_file_path
            - name: IMAGE_FETCH_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: image_fetch_path
            - name: BACKEND_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: backend_service_url
