apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-app-backend-postgres-secret
data:
    postgres_password: ENC[AES256_GCM,data:r//BpEk9lq02ZIQuaGF2rA==,iv:XvLYVHZ8ggwiAM0A4J5S6Bbwyzjyjj4V7J1fweQUchY=,tag:u9wttSB5Tkgmi9BNAuUY4g==,type:str]
sops:
    age:
        - recipient: age1fw5g4xg8n97slygmkaspyzs4jla3f73zxr9jh37hg9j05u2rr92q0jrwcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V2lIMUZ5Rmt4TEF5ZnNB
            RWZleEsyRGgzNW5XTlhOM2Q1ZHlBSzRiNTNBClg3THBwQUYvcnhMQ1NYZC9KU1lz
            NUx3Um8vWVdHTndQT05aWENvK1laczAKLS0tIDFLdkxKRzZGa0dNVjhmZEtZc1Ur
            YnFEQ3kySDNHa1VjemV2czRhN1piM1kK+mj44Yf/TkYgq+cDBIR7jLyAjXn6nNLY
            zv4chs10PhobsK/DSMucneBgKKXXQR47CtlyQxS4D0Ie8SPNaYO+Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:25:15Z"
    mac: ENC[AES256_GCM,data:+lKSEdsweLhrZbeFIMZ2dRTjsBSJHpCdjfKnTPP8MXpxVyLAP30QaYoidW28xWNbDthHkH7PxYexitRP2SrNhgIDqQDfDadhCRB2vM9eQQ4RCHJ3xQx1jw3OstG3asaF47nDJIw1l2Uoe7jEL/OKiMdC3dE3f7ajc2Ffckt0Xe4=,iv:KMDVKiJQP/9EQ24ujY9O3V10//GO+N0OnrYGXgtLgTA=,tag:S9bcPqJ9uDIEb1GRyF/l/Q==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.1
